name: Triggered by Dispatch

on:
  repository_dispatch:
    types: [trigger-open-pr-check]

jobs:
  run-on-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Info
        run: echo "Triggered by dispatch with payload: ${{ toJson(github.event.client_payload) }}"
