
name: PR Review Dispatcher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: string
      branch_name:
        description: 'Branch Name'
        required: true
        type: string

jobs:
  review-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: Simulate Validation Step
        run: |
          PR_NUMBER="${{ github.event.inputs.pr_number || github.event.pull_request.number || 'N/A' }}"
          BRANCH_NAME="${{ github.event.inputs.branch_name || github.head_ref || github.ref_name || 'N/A' }}"
          echo "Validating PR #${PR_NUMBER} on branch ${BRANCH_NAME}"

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."

      - name: Fetch PR Metadata
        id: fetch_pr
        run: |
          PR_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ inputs.pr_number }}"
          echo "Fetching PR metadata from $PR_URL"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }} "                -H "Accept: application/vnd.github+json"                $PR_URL > pr_metadata.json
          cat pr_metadata.json

      - name: Post Comment on PR
        run: |
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.pr_number }}/comments"
          COMMENT_BODY='{"body": "Automated review triggered for PR #${{ inputs.pr_number }} on branch ${{ inputs.branch_name }}"}'
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"                -H "Accept: application/vnd.github+json"                -d "$COMMENT_BODY" $COMMENT_URL
